<?php



$form = $this->get('form');

// $form->setAttributes([
//     'class' => 'fom-horizontal',
//     'id' => 'login-form',
//    // 'action' => '#',
// ]);

$username = $form->get('username');
$password = $form->get('password');
$btnSubmit = $form->get('btnSubmit');

$form->prepare();
?>

<div class="row">
   
        <?= $this->form()->openTag($form) ?>
        
        <div class="form-group">
         <?= $this->formLabel($username) ?>
            <?= $this->formText($username)  ?>
            <?= $this->formElementErrors($username) ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($password) ?>
            <?= $this->formPassword($password)  ?>
            <?= $this->formElementErrors($password) ?>

        </div>
        <div class="form-group">
            <?= $this->flashMessenger()->render('error', ['alert', 'alert-danger']) ?>
        </div>

        <!-- /.box-body -->
        <div class="form-group">

            <?= $this->formSubmit($btnSubmit) ?>

        </div>
        <?= $this->form()->closeTag($form) ?>
    
</div>