
<?php
$title = "Thêm Mới user";
$this->headTitle($title);
$form = $this->get('form');
$TenKH = $form->get('makh');
$ngaydat = $form->get('ngaydat');
// $confirm_password = $form->get('confirm_password');
// $Hoten = $form->get('Hoten');
// $ngaysinh = $form->get('NgaySinh');
 $btnSubmit = $form->get('btnSubmit');

$form->prepare();
?>

<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title"><?= $title ?></h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <?= $this->form()->openTag($form) ?>
    <div class="box-body">
        <div class="form-group">
            <?= $this->formLabel($makh) ?>
            <?= $this->formText($makh)  ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($ngaydat) ?>
            <?= $this->formText($ngaydat)  ?>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
        <?= $this->formSubmit($btnSubmit) ?>
    </div>
    <?= $this->form()->closeTag($form) ?>
</div>

