<?php 
$title= "Đăng ký đặt phòng";
$this -> headTitle($title);


?>
<div class="container-fluid">
    <div class="row page-title-div">
        <div class="col-md-6">
            <h2 class="title"><?=$title?></h2>
            <p class="sub-title"><?= $this->flashMessenger()->render('success', ['alert', 'alert-success']);?></p>
        </div>
                <!-- /.col-md-6 -->
        
                                <!-- /.col-md-6 text-right -->
     </div>
 </div>
  



<section class="section">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-9 col-md-offset-2">
<table class="table table-striped table-bordered" id="example" >
    <thead>
        <tr>
            <th>STT</th>
            <th>Tên Khách Hàng</th>
            <th>Ngày đến</th>
            <th>Ngày đi</th>
            <th>Ghi chú</th>
            <th>Loại phòng</th>
            <th>Khách sạn</th>
            <th>Option</th>
            
            
        </tr>
    </thead>
    <tbody> 
        <?php 
        $stt=1;
        foreach($dkdps as $dkdp=>$value):?>
        <tr>
            <td><?=$stt?></td>
            <td><?=$this->escapeHtml($value['tenkh'])?></td>
            
            <td><?=$this->escapeHtml($value['ngayo'])?></td>
            <td><?=$this->escapeHtml($value['Ngaydi'])?></td>
            <td><?=$this->escapeHtml($value['ghichu'])?></td>
            <td><?=$this->escapeHtml($value['TenLP'])?></td>
            <td><?=$this->escapeHtml($value['tenKS'])?></td>
           
            <td> 
                <a href="<?=$this->url('dangkydatphong',['action'=>'delete','id'=>$this->escapeHtml($value['id'])])?>"> 
                <button type="button" class="btn btn-danger" >Delete </a>

            </td>
            
        </tr>
        <?php
        $stt++;
        endforeach?>
    </tbody>
</table>
        </div>
    </div>
</div>
</section>