<?php 
$title= "Danh Sách Khách Sạn ";
$this -> headTitle($title);

?>
<div class="container-fluid">
    <div class="row page-title-div">
        <div class="col-md-6">
            <h2 class="title"><?=$title?></h2>
            <p class="sub-title"><?= $this->flashMessenger()->render('success', ['alert', 'alert-success']);?></p>
        </div>
                <!-- /.col-md-6 -->
        <div class="col-md-6 right-side">
            <a class="btn btn-primary" role="button" href="<?=$this->url('khachsan',['action'=>'add'])?>" >Thêm khách sạn</a>
         </div>
                                <!-- /.col-md-6 text-right -->
     </div>
 </div>

<section class="section">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <table class="table table-striped table-bordered" id="example" >
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Tên khách sạn</th>
                            <th>Địa Chỉ</th>
                            <th>Hình Khách sạn</th>
                            <th>Tên thành phố</th>
                            <th>Option</th>
 
                        </tr>
                    </thead>
                    <tbody> 
                        <?php 
                        $stt=1;
                        foreach($khachsans as $khachsan=> $value ):?>
                        
                        <tr>
                            <td><?=$this->escapeHtml($value['idKS'])?></td>  
                            <td><?=$this->escapeHtml($value['tenKS'])?></td>
                            <td><?=$this->escapeHtml($value['DiaChi'])?></td>
                            <td><img src="/../zendne5/images/khachsan/<?= $value['HinhKS'] ?>" width="80px" height="80px"></td>
                            <td><?=$this->escapeHtml($value['TenTP'])?></td>  
                            
                            <td> 
                                <a href="<?=$this->url('khachsan',['action'=>'edit','id'=>$this->escapeHtml($value['idKS'])])?>"> 
                                <button class="btn btn-primary">Edit </a> | 
                                <a href="<?=$this->url('khachsan',['action'=>'delete','id'=>$this->escapeHtml($value['idKS'])])?>"> 
                                <button class="btn btn-danger">Delete </a>

                            </td>
                        </tr>
                        <?php
                        $stt++;
                        endforeach?>
                    </tbody>
</table>
</div>
    </div>
</div>
</section>